sudo: required

language: bash

services:
  - docker

before_install:
  - docker pull koalaman/shellcheck

script:
  - docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/idoit
  - docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/idoit-backup
  - docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/idoit-install.sh
  - docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/idoit-jobs
  - docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/idoit-restore

matrix:
  fast_finish: true

notifications:
  email:
    on_success: never
    on_failure: always
