sudo: required

language: bash

services:
  - docker

before_install:
  - docker pull koalaman/shellcheck

script:
  - docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/idoit*

matrix:
  fast_finish: true

notifications:
  email:
    on_success: never
    on_failure: always
