os: xenial

language: node_js

node_js:
  - "lts/*"

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker version
  - npm i -g npm@6
  - npm install
  - docker pull koalaman/shellcheck

script:
  - docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/i-doit.sh
  - docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/idoit
  - docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/idoit-backup
  - docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/idoit-hotfix
  - docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/idoit-install
  - docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/idoit-jobs
  - docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/idoit-pwd
  - docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/idoit-restore
  - docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/idoit-support
  - make lint-markdown
  - make lint-yaml
  - npm audit

notifications:
  email:
    on_success: never
    on_failure: always
