sudo: required

language: bash

services:
  - docker

before_install:
  - docker pull koalaman/shellcheck

script:
  - docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/idoit
  - docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/idoit-backup
  - docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/idoit-hotfix
  - docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/idoit-install
  - docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/idoit-jobs
  - docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/idoit-pwd
  - docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/idoit-restore
  - docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/idoit-support

matrix:
  fast_finish: true

notifications:
  email:
    on_success: never
    on_failure: always
